name: Release New Version
on:
  release:
    types: [published]
    branches:
      - 'main'

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: data-prd
    steps:
      - name: deploy
        run: echo "I've run"
